import { mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * One-shot migration: backfill the `provider` field on usageRecords rows that
 * were written before the field was introduced. All pre-existing data was
 * generated by the Claude provider, so every row gets `provider: "claude"`.
 *
 * Call this in a loop from scripts/migrate-usage-provider.ts until
 * `remaining === 0`.
 */
export const backfillUsageProvider = mutation({
  args: {
    batchSize: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const batchSize = args.batchSize ?? 100;

    // Collect a batch of rows that are missing the provider field.
    // There is no index on undefined values, so we do a table scan with filter.
    const batch = await ctx.db
      .query("usageRecords")
      .filter((q) => q.eq(q.field("provider"), undefined))
      .take(batchSize);

    for (const doc of batch) {
      await ctx.db.patch(doc._id, { provider: "claude" });
    }

    // Check how many remain (one extra take to detect "done").
    const remaining = await ctx.db
      .query("usageRecords")
      .filter((q) => q.eq(q.field("provider"), undefined))
      .take(1);

    return {
      migrated: batch.length,
      remaining: remaining.length,
    };
  },
});
